### ISSUE TITLE
Request: Better build instructions

### ISSUE THREAD

**Issue by kjoller** [stakater/Xposer#19]
A small 'how to build'-section for the README.md would be greatly appreciated. I have not been succesful in building the project. I am a Go-n00b, so that may just be the main cause.

Two hurdles so far:

First, internal/pkg/config/utils.go seems to be named " utils.go" (with a space in front), causing an error.

```
github.com/stakater/Xposer/internal/pkg/cmd/xposer.go:9:2: invalid input file name " utils.go"
```

With that renamed, build result in this:
 
```
# github.com/stakater/Xposer/internal/pkg/routes
github.com/stakater/Xposer/internal/pkg/routes/routes.go:12:3: cannot use "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/openshift/api/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
github.com/stakater/Xposer/internal/pkg/routes/routes.go:25:5: cannot use "k8s.io/apimachinery/pkg/util/intstr".FromInt(servicePort) (type "k8s.io/apimachinery/pkg/util/intstr".IntOrString) as type "github.com/openshift/api/vendor/k8s.io/apimachinery/pkg/util/intstr".IntOrString in field value
```

I have tried ```go get github.com/stakater/Xposer```, as well as cloning the repo into ```$GOPATH/src/github.com/stakater/Xposer``` and running ```glide install```.

**Comment by ahsan-storm** [comment]
can you try `glide install --strip-vendor`

**Comment by kjoller** [comment]
@ahsan-storm That made it work, thank you very much.

I still need to rename ' utils.go' to 'utils.go', but after that, it seems to be smooth sailing.

And also, I found  ```make binary-image``` to be much easier than building locally, and that does not seem to need any renaming of files.
